# i/o
model_path: '../../../workspace/med/models'
data_path: '../../../workspace/med/data'

# eval and logging
eval_interval: 250
eval_iters: 100
wandb_project: 'roberta-tuning'
wandb_run_name: 'roberta-med'

# model config
num_layers: 12
num_heads: 12
hidden_size: 768
batch_size: 16
block_size: 512

# optimizer settings
learning_rate: 5e-5 # max learning rate
max_iters: 100000 # total number of training iterations
weight_decay: 1e-2
beta1: 0.9
beta2: 0.999
gradient_accumulation_steps: 5 * 2 # 5 grad accum * 6 gpus
grad_clip: 1.0

# DDP settings
backend: 'nccl' # 'nccl', 'gloo', etc.
device: 'cuda' # examples: 'cpu', 'cuda', 'cuda:0', 'cuda:1', etc.
dtype: 'bfloat16' # 'float32' or 'bfloat16'

# resume?
resume_from_checkpoint: null
last_iter: null